### ISSUE TITLE
doesn't work on greasemonkey

### ISSUE THREAD

**Issue by binex-dsk** [7kt-swe/7ktTube#23]
```
Uncaught TypeError: Cannot read property 'removeAttribute' of undefined
    at userscript:GM-STILL_ALIVE/7ktTube | 2016 REDUX:233
    at userscript:GM-STILL_ALIVE/7ktTube | 2016 REDUX:22270
(anonymous) @ userscript:GM-STILL_ALIVE/7ktTube | 2016 REDUX:233
(anonymous) @ userscript:GM-STILL_ALIVE/7ktTube | 2016 REDUX:22270
```

**Comment by BowDown097** [comment]
deprecatedmonkey user lol

**Comment by 7kt-swe** [comment]
Never has and never will.

**Comment by binex-dsk** [comment]
> Never has and never will.

Why not? I'd like to use this on qutebrowser.

**Comment by 7kt-swe** [comment]
> > Never has and never will.
> 
> Why not? I'd like to use this on qutebrowser.

Because greasemonkey doesn't even support a third of the source code and it's features. 
Google a comparison between Violentmonkey and Greasemonkey...

**Comment by binex-dsk** [comment]
> > > Never has and never will.
> > 
> > Why not? I'd like to use this on qutebrowser.
> 
> Because greasemonkey doesn't even support a third of the scripts source code and features. 
> Google a comparison between Violentmonkey and Greasemonkey...

Glad to see you don't care about people using actually good browsers. :)

**Comment by 7kt-swe** [comment]
It's  impossible to make this to work in greasemonkey because of the greasemonkey requirements for security.
Learn about the subject before saying stupid shit like I don't care..
I make this with zero profit on my spare time.
Have a wonderful day.. DOUCHEBAG

**Comment by BowDown097** [comment]
> > > > Never has and never will.
> > > 
> > > 
> > > Why not? I'd like to use this on qutebrowser.
> > 
> > 
> > Because greasemonkey doesn't even support a third of the scripts source code and features.
> > Google a comparison between Violentmonkey and Greasemonkey...
> 
> Glad to see you don't care about people using actually good browsers. :)

cope

**Comment by THErlego** [comment]
quite the extreme responses
but its the browser developers problem for only supporting such an outdated extension manager
