### ISSUE TITLE
Subscribe button cut in half

### ISSUE THREAD

**Issue by AshtyBoi** [7kt-swe/7ktTube#25]
There has seemingly been a new layout update to 7ktTube that styled the page info. Like this:
![image](https://user-images.githubusercontent.com/107463768/173933080-cbf97e98-51cf-4f68-a69d-60ff622566fe.png)
But, as you can see here, it has made the subscribe text and button appear to be far away from each other.
![image](https://user-images.githubusercontent.com/107463768/173932619-dd401d08-097f-48eb-a401-04769604c254.png)
Please fix this.

**Comment by 7kt-swe** [comment]
This has never occurred to me..
I just checked Firefox, Chrome and Edge, they all looks perfectly fine to me .

![bild](https://user-images.githubusercontent.com/85538951/173955682-638d093e-a299-439e-a2e5-852bbf8f315b.png)

**Comment by AshtyBoi** [comment]
This only seems to happen when I'm on the new video page design (you can tell by the font and the absence of the more button), but it's still styled like the old one for some reason. This started about a day ago, and it looks okay when I'm subscribed to a channel, but it doesn't look okay when I'm not subscribed to a channel.

**Comment by BowDown097** [comment]
Ya this is an issue with the new watch page design. It breaks this one thing and I don't know why and I don't think it can be fixed without doing some retarded stuff (which might have to be done anyway)
